apiVersion: "cluster.giantswarm.io/v1"
kind: Aws
metadata:
  name: ${CLUSTER_NAME}
spec:
  cluster:
    cluster:
      id: "${CLUSTER_NAME}"

    customer:
      id: "example-customer"

    docker:
      imageNamespace: "giantswarm"

    etcd:
      domain: "etcd.${CLUSTER_NAME}.${COMMON_DOMAIN}"
      prefix: "${CLUSTER_NAME}"
      port: 2379

    calico:
      subnet: "192.168.0.0"
      cidr: 24
      mtu: 1500

    kubernetes:
      api:
        domain: "api.${CLUSTER_NAME}.${COMMON_DOMAIN}"
        insecurePort: 8080
        securePort: 443
        clusterIPRange: "192.168.0.0/24"
      dns:
        ip: "172.29.0.10"
      hyperkube:
        docker:
          image: "giantswarm/hyperkube:v1.5.2_coreos.0"
      ingressController:
        insecurePort: 30010
        securePort: 30011
        domain: "ingress.${CLUSTER_NAME}.${COMMON_DOMAIN_INGRESS}"
      kubelet:
        port: 10250
      networkSetup:
        docker:
          image: "giantswarm/k8s-setup-network-environment:ba2b57155d859a1fc5d378c2a09a77d7c2c755ed"

    masters:
    - hostname: "master-1"

    workers:
    - hostname: "worker-1"

  aws:
    region: "${AWS_REGION}"
    az: "${AWS_AZ}"
    vpc:
      cidr: "10.0.0.0/16"
      privateSubnetCidr: "10.0.0.0/19"
      publicSubnetCidr: "10.0.128.0/20"

    masters:
    - imageid: "${AWS_AMI}"
      instancetype: "${AWS_INSTANCE_TYPE_MASTER}"

    workers:
    - imageid: "${AWS_AMI}"
      instancetype: "${AWS_INSTANCE_TYPE_WORKER}"
