apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aws-operator-local
  labels:
    app: aws-operator-local
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aws-operator-local
    spec:
      volumes:
      - name: aws-operator-configmap
        configMap:
          name: aws-operator-configmap
          items:
          - key: config.yaml
            path: config.yaml
      - name: ssh-key
        configMap:
          name: aws-operator-ssh-key-configmap
          items:
          - key: id_rsa.pub
            path: id_rsa.pub
      - name: certs
        hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
      # See https://github.com/giantswarm/aws-operator/pull/36#discussion_r105404746
      containers:
      - name: aws-operator
        image: quay.io/giantswarm/aws-operator:local-dev
        volumeMounts:
        - name: aws-operator-configmap
          mountPath: /var/run/aws-operator/configmap/
        - name: certs
          mountPath: /etc/ssl/certs/ca-certificates.crt
        - name: ssh-key
          mountPath: /.ssh/
          readOnly: true
        ports:
        - name: http
          containerPort: 8000
        args:
        - daemon
        - --config.dirs=/var/run/aws-operator/configmap/
        - --config.files=config
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 250m
            memory: 250Mi
      imagePullSecrets:
      - name: giantswarm-registry
