{{define "main"}}AWSTemplateFormatVersion: 2010-09-09
Description: Main CloudFormation stack.
Resources:
  PeerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: Peer-{{ .ClusterID }}
      AssumeRolePolicyDocument:
        Statement:
          - Principal:
              AWS: {{ .GuestAccountID }}
            Action:
              - 'sts:AssumeRole'
            Effect: Allow
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'ec2:AcceptVpcPeeringConnection'
                Resource: '*'
{{end}}
