apiVersion: v1
kind: Service
metadata:
  name: aws-operator
  namespace: giantswarm
  labels:
    app: aws-operator
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    app: aws-operator
