apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: aws-operator-secret
  namespace: giantswarm
data:
  secret.yaml: {{ .Values.Installation.V1.Secret.AWSOperator.SecretYaml | b64enc | quote }}
