apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: credential-default
  namespace: giantswarm
  labels:
    app: credentiald
    giantswarm.io/managed-by: credentiald
    giantswarm.io/organization: giantswarm
    giantswarm.io/service-type: system
data:
  aws.admin.arn: {{ .Values.Installation.V1.Secret.AWSOperator.CredentialDefault.AdminARN | b64enc }}
  aws.awsoperator.arn: {{ .Values.Installation.V1.Secret.AWSOperator.CredentialDefault.AWSOperatorARN | b64enc }}
