apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: aws-operator-ssh-key-secret
  namespace: giantswarm
data:
  id_rsa.pub: {{ .Values.Installation.V1.Secret.AWSOperator.IDRSAPub | b64enc | quote }}
