apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-operator-configmap
  namespace: giantswarm
data:
  config.yaml: |
    server:
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      aws:
        region: '{{ .Values.Installation.V1.Provider.AWS.Region }}'
      installation:
        name: '{{ .Values.Installation.V1.Name }}'
      kubernetes:
        incluster: true
