apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-operator
rules:
  - apiGroups:
      - cluster.giantswarm.io
    resources:
      - awses
    verbs:
      - "*"
  - apiGroups:
      - cluster.k8s.io
    resources:
      - clusters
      - clusters/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cluster.k8s.io
    resources:
      - machinedeployments
      - machinedeployments/status
    verbs:
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - extensions
    resources:
      - thirdpartyresources
    verbs:
      - "*"
  - apiGroups:
      - provider.giantswarm.io
    resources:
      - awsconfigs
      - awsconfigs/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - provider.giantswarm.io
    resources:
      - awsconfigs/status
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - core.giantswarm.io
    resources:
      - nodeconfigs
    verbs:
      - "*"
  - apiGroups:
      - core.giantswarm.io
    resources:
      - drainerconfigs
    verbs:
      - "*"
  # TODO drop create and delete permissions for namespaces when
  # legacy bundles are gone and clusterapi bundle v29 is the latest version.
  #
  #     https://github.com/giantswarm/giantswarm/issues/6829
  #
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - create
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - endpoints
      - services
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - aws-operator-configmap
    verbs:
      - get
  - nonResourceURLs:
      - "/"
      - "/healthz"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-operator
subjects:
  - kind: ServiceAccount
    name: aws-operator
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: aws-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-operator-psp
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - aws-operator-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-operator-psp
subjects:
  - kind: ServiceAccount
    name: aws-operator
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: aws-operator-psp
  apiGroup: rbac.authorization.k8s.io
