apiVersion: v1
kind: Service
metadata:
  name: aws-operator
  namespace: {{ .Values.namespace }}
  labels:
    app: aws-operator
    version: {{ .Chart.Version }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 8000
  selector:
    app: aws-operator
    version: {{ .Chart.Version }}
