AWSTemplateFormatVersion: 2010-09-09
Description: Workers ASG
Parameters:
  SubnetID:
    Type: "AWS::EC2::Subnet::Id"
    Description: The SubnetId in your Virtual Private Cloud (VPC)
    ConstraintDescription: >-
      must be a list of at least two existing subnets associated with at least
      two different availability zones. They should be residing in the selected
      Virtual Private Cloud.
  AZ:
    Type: "AWS::EC2::AvailabilityZone::Name"
  InstanceType:
    Description: Worker EC2 instance type
    Type: String
    Default: m3.medium
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - m1.small
      - m1.medium
      - m1.large
      - m1.xlarge
      - m2.xlarge
      - m2.2xlarge
      - m2.4xlarge
      - m3.medium
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
    ConstraintDescription: must be a valid EC2 instance type.
  SecurityGroupID:
    Description: The ID of the workers security group
    Type: AWS::EC2::SecurityGroup::Id
  LoadBalancerName:
    Description: The name of the ingress load balancer
    Type: String
  ImageID:
    Description: The AMI for the worker instances
    Type: String
  ASGMinSize:
    Type: Number
  ASGMaxSize:
    Type: Number
  HealthCheckGracePeriod:
    Type: Number
  SmallCloudConfig:
    Type: String
  IAMInstanceProfileName:
    Type: String
  KeyName:
    Type: String
    Description: The name of the KeyPair containing the SSH key
  AssociatePublicIPAddress:
    Type: String
    AllowedValues: [ true, false ]
Resources:
  WorkersLaunchConfiguration:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Description: Workers LaunchConfiguration
    Properties:
      ImageId: !Ref ImageID
      SecurityGroups:
      - !Ref SecurityGroupID
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref IAMInstanceProfileName
      BlockDeviceMappings:
      - DeviceName: "/dev/xvdh"
        Ebs:
          VolumeSize: '50'
          VolumeType: gp2
      AssociatePublicIpAddress: !Ref AssociatePublicIPAddress
      UserData: !Ref SmallCloudConfig
      KeyName: !Ref KeyName
  WorkersASG:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      VPCZoneIdentifier:
        - !Ref SubnetID
      AvailabilityZones:
        - !Ref AZ
      MinSize: !Ref ASGMinSize
      MaxSize: !Ref ASGMaxSize
      LaunchConfigurationName: !Ref WorkersLaunchConfiguration
      LoadBalancerNames:
        - !Ref LoadBalancerName
      HealthCheckGracePeriod: !Ref HealthCheckGracePeriod
    UpdatePolicy:
      AutoScalingRollingUpdate:
        # minimum amount of instances that must always be running during a rolling update
        MinInstancesInService: 2
        # only do a rolling update of this amount of instances max
        MaxBatchSize: 2
        # after creating a new instance, pause operations on the ASG for this amount of time
        PauseTime: PT10S
