version: 1

outOfClusterTest:
  - run: helm registry install quay.io/giantswarm/aws-operator-lab-chart -- --set imageTag=${CIRCLE_SHA1}
    waitFor:
      run: kubectl get pods
      match: aws-operator-local-.*\s*1/1\s*Running

inClusterTest:
  enabled: false
