version: 1

setup:
  - run: kubectl create namespace giantswarm
    waitFor:
      run: kubectl get namespace
      match: giantswarm\s*Active

outOfClusterTest:
  - run: |
      cat <<EOF > ./values.yaml
      Installation:
        V1:
          Secret:
            AWSOperator:
              IDRSAPub: myidrsa
              SecretYaml: |
                service:
                  aws:
                    accesskey:
                      id: ""
                      secret: ""
                    hostaccesskey:
                      id: ""
                      secret: ""
            Registry:
              PullSecret:
                DockerConfigJSON: "{\"auths\":{\"quay.io\":{\"auth\":\"$REGISTRY_PULL_SECRET\"}}}"
      EOF
      helm registry install quay.io/giantswarm/aws-operator-chart@1.0.0-${CIRCLE_SHA1} -- --values=values.yaml -n aws-operator-chart

    waitFor:
      run: kubectl get pods -n giantswarm
      match: aws-operator-.*\s*1/1\s*Running
