{{define "internet_gateway"}}
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: {{ .ClusterID }}

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment 
    Properties:
      InternetGatewayId:
        Ref: InternetGateway
      VpcId: {{ .VPCID }}

{{end}}
