{{define "load_balancers"}}
  ApiLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      ConnectionSettings:
        IdleTimeout: {{ .APIElbIdleTimoutSeconds }}
      HealthCheck:
        HealthyThreshold: {{ .ELBHealthCheckHealthyThreshold }}
        Interval: {{ .ELBHealthCheckInterval }}
        Target: {{ .APIElbHealthCheckTarget }}
        Timeout: {{ .ELBHealthCheckTimeout }}
        UnhealthyThreshold: {{ .ELBHealthCheckUnhealthyThreshold }}
      Instances:
      - !Ref MasterInstance
      Listeners:
      {{ range .APIElbPortsToOpen}}
      - InstancePort: {{ .PortInstance }}
        InstanceProtocol: TCP
        LoadBalancerPort: {{ .PortELB }} 
        Protocol: TCP
      {{ end }}
      LoadBalancerName: {{ .APIElbName }}
      Scheme: {{ .APIElbScheme }}
      SecurityGroups:
        - {{ .APIElbSecurityGroupID }}
      Subnets:
        - {{ .APIElbSubnetID }}
{{end}}
