{{define "subnets"}}
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: {{ .PrivateSubnetAZ }}
      CidrBlock: {{ .PrivateSubnetCIDR }}
      MapPublicIpOnLaunch: {{ .PrivateSubnetMapPublicIPOnLaunch }}
      Tags:
      - Key: Name
        Value: {{ .PrivateSubnetName }}
      VpcId: {{ .VPCID }}

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet
{{end}}
