apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.resource.default.name | tpl }}
  namespace: {{ .Values.resource.default.namespace | tpl }}
data:
  secret.yaml: {{ .Values.Installation.V1.Secret.AWSOperator.SecretYaml | b64enc | quote }}
