apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: aws-operator-secret.v[[ .Version ]]
  namespace: {{ .Values.namespace }}
data:
  secret.yaml: {{ .Values.Installation.V1.Secret.AWSOperator.SecretYaml | b64enc | quote }}
