apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  aws-secret.yaml: {{ .Values.Installation.V1.Secret.AWSOperator.SecretYaml | b64enc | quote }}
  dockerhub-secret.yaml: {{ printf "service:\n  registry:\n    dockerhubToken: %q" .Values.Installation.V1.Secret.Registry.Dockerhub.Token | b64enc | quote }}
