apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    {{- include "aws-operator.labels" . | nindent 4 }}
