apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "aws-operator.labels" . | nindent 4 }}
