apiVersion: "cluster.giantswarm.io/v1"
kind: Aws
metadata:
  name: test
spec:
  cluster:
    cluster:
      id: "example-cluster"

    customer:
      id: "example-customer"

    masters:
    - hostname: "master-1"
    - hostname: "master-2"
    - hostname: "master-3"

    workers:
    - hostname: "worker-1"

  aws:
    region: "eu-central-1"
    az: "a"
    masters:
    - imageid: "ami-9501c8fa"
      instancetype: "t2.medium"
    - imageid: "ami-9501c8fa"
      instancetype: "t2.medium"
    - imageid: "ami-9501c8fa"
      instancetype: "t2.medium"

    workers:
    - imageid: "ami-9501c8fa"
      instancetype: "t2.medium"
