apiVersion: "cluster.giantswarm.io/v1"
kind: Aws
metadata:
  name: test
spec:
  cluster:
    cluster:
      id: "example-cluster"

    customer:
      id: "example-customer"

    docker:
      imageNamespace: "giantswarm"

    etcd:
      domain: "k8s.cluster.giantswarm.io"
      prefix: "example-cluster"

    calico:
      subnet: "192.168.0.0"
      cidr: 24
      mtu: 1500

    kubernetes:
      api:
        domain: "k8s.cluster.giantswarm.io"
        insecurePort: 8080
        securePort: 443
        clusterIPRange: "192.168.0.0/24"
      hyperkube:
        docker:
          image: "giantswarm/hyperkube:v1.5.2_coreos.0"

    operator:
      networkSetup:
        docker:
          image: "giantswarm/setup-network-env:0.1"

    masters:
    - hostname: "master-1"

    workers:
    - hostname: "worker-1"

  aws:
    region: "eu-central-1"
    az: "eu-central-1a"
    vpc:
      cidr: "10.0.0.0/16"
      privateSubnetCidr: "10.0.0.0/19"
      publicSubnetCidr: "10.0.128.0/20"

    masters:
    - imageid: "ami-9501c8fa"
      instancetype: "t2.medium"

    workers:
    - imageid: "ami-9501c8fa"
      instancetype: "t2.medium"
