apiVersion: "cluster.giantswarm.io/v1"
kind: Aws
metadata:
  name: test
spec:
  cluster:
    id: "example-cluster"

  customer:
    id: "example-customer"

  masters:
  - imageid: "ami-6f68cf0f"
    instancetype: "t2.medium"
  - imageid: "ami-6f68cf0f"
    instancetype: "t2.medium"
  - imageid: "ami-6f68cf0f"
    instancetype: "t2.medium"

  workers:
  - imageid: "ami-6f68cf0f"
    instancetype: "t2.medium"
