apiVersion: v1
kind: Secret
metadata:
    name: example-api-secret
    labels:
        clusterComponent: api
        clusterID: example-cluster
type: Opaque
data:
    crt: Zm9vYmFyCg==
    ca: Zm9vYmFyCg==
    key: Zm9vYmFyCg==
---
apiVersion: v1
kind: Secret
metadata:
    name: example-worker-secret
    labels:
        clusterComponent: worker
        clusterID: example-cluster
type: Opaque
data:
    crt: Zm9vYmFyCg==
    ca: Zm9vYmFyCg==
    key: Zm9vYmFyCg==
---
apiVersion: v1
kind: Secret
metadata:
    name: example-calico-secret
    labels:
        clusterComponent: calico
        clusterID: example-cluster
type: Opaque
data:
    crt: Zm9vYmFyCg==
    ca: Zm9vYmFyCg==
    key: Zm9vYmFyCg==
---
apiVersion: v1
kind: Secret
metadata:
    name: example-etcd-secret
    labels:
        clusterComponent: etcd
        clusterID: example-cluster
type: Opaque
data:
    crt: Zm9vYmFyCg==
    ca: Zm9vYmFyCg==
    key: Zm9vYmFyCg==
---
apiVersion: v1
kind: Secret
metadata:
    name: example-service-account-secret
    labels:
        clusterComponent: service-account
        clusterID: example-cluster
type: Opaque
data:
    crt: Zm9vYmFyCg==
    ca: Zm9vYmFyCg==
    key: Zm9vYmFyCg==
