version: 2
update_configs:
  - package_manager: "go:modules"
    reviewers:
      - "giantswarm/team-firecracker-pe"
    directory: "/"
    ignored_updates:
      - match:
          dependency_name: "k8s.io/*"
          version_requirement: ">=0.17.0"
    update_schedule: "weekly"
