version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "daily"
    ignored_updates:
      - match:
          # Ignore k8s.io dependencies
          dependency_name: "k8s.io/*"

