clusterName: "test-cluster"
commonDomain: "aws.gigantic.io"
sshUser: "test-user"
sshPublicKey: "ssh-rsa XXXXXXXXXXXXXXXXXXXXXXXXX"
encryptionKey: "QitRZGlWeW5WOFo2YmdvMVRwQUQ2UWoxRHZSVEF4MmovajlFb05sT1AzOD0="
clusterVersion: "v_0_1_0"

aws:
  region: "eu-central-1"
  az: "eu-central-1a"
  ami: "ami-d60ad6b9"
  instanceTypeMaster: "m3.large"
  instanceTypeWorker: "m3.large"

  apiHostedZone: "Z*************"
  ingressHostedZone: "Z*************"
  routeTable0: "example-table"
  routeTable1: "example-table-two"
  vpcPeerId: "vpc-XXXXXXXXX"
