version: 1

test:
  env:
    - "VAULT_TOKEN=mytoken"
    - "CIRCLE_SHA1=${CIRCLE_SHA1}"
    - "COMMON_DOMAIN_GUEST=${COMMON_DOMAIN_GUEST}"
    - "CLUSTER_NAME=${CLUSTER_NAME}"
    - "TESTED_VERSION=${TESTED_VERSION}"
    - "REGISTRY_PULL_SECRET=${REGISTRY_PULL_SECRET}"
    - "IDRSA_PUB=${IDRSA_PUB}"
    - "AWS_ACCESS_KEY_ID_GUEST=${AWS_ACCESS_KEY_ID_GUEST}"
    - "AWS_SECRET_ACCESS_KEY_GUEST=${AWS_SECRET_ACCESS_KEY_GUEST}"
    - "AWS_SESSION_TOKEN_GUEST=${AWS_SESSION_TOKEN_GUEST}"
    - "AWS_ACCESS_KEY_ID_HOST=${AWS_ACCESS_KEY_ID_HOST}"
    - "AWS_SECRET_ACCESS_KEY_HOST=${AWS_SECRET_ACCESS_KEY_HOST}"
    - "AWS_SESSION_TOKEN_HOST=${AWS_SESSION_TOKEN_HOST}"
    - "AWS_REGION=${AWS_REGION}"
    - "AWS_API_HOSTED_ZONE_GUEST=${AWS_API_HOSTED_ZONE_GUEST}"
    - "AWS_INGRESS_HOSTED_ZONE_GUEST=${AWS_INGRESS_HOSTED_ZONE_GUEST}"
