version: 1

test:
  env:
    - "VAULT_TOKEN=mytoken"
    - "CIRCLE_SHA1=${CIRCLE_SHA1}"
    - "COMMON_DOMAIN=${COMMON_DOMAIN}"
    - "CLUSTER_NAME=${CLUSTER_NAME}"
    - "TESTED_VERSION=${TESTED_VERSION}"
    - "REGISTRY_PULL_SECRET=${REGISTRY_PULL_SECRET}"
    - "IDRSA_PUB=${IDRSA_PUB}"
    - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
    - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
    - "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}"
    - "AWS_REGION=${AWS_REGION}"
    - "AWS_API_HOSTED_ZONE=${AWS_API_HOSTED_ZONE}"
    - "AWS_INGRESS_HOSTED_ZONE=${AWS_INGRESS_HOSTED_ZONE}"
